---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
labels:
  org.opencontainers.image.title: Technitium DNS Server
  org.opencontainers.image.description: An open source authoritative as well as recursive DNS server
  org.opencontainers.image.source: https://technitium.com/dns/
  org.opencontainers.image.licenses: GPL-3.0
